defmodule AshClickhouse.TestRepo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_clickhouse.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    CREATE TABLE users (
      id UUID DEFAULT generateUUIDv4(),
      name String,
      email String,
      age UInt8,
      score Float64,
      is_active Bool,
      inserted_at DateTime64(6, 'UTC'),
      updated_at DateTime64(6, 'UTC')
    ) ENGINE = MergeTree()
        ORDER BY email
    """

    execute """
    CREATE TABLE organizations (
      id UUID DEFAULT generateUUIDv4(),
      name String,
      industry String,
      employee_count UInt32,
      founded_year UInt16,
      inserted_at DateTime64(6, 'UTC'),
      updated_at DateTime64(6, 'UTC')
    ) ENGINE = MergeTree()
        ORDER BY name
    """

    execute """
    CREATE TABLE organization_users (
      user_id UUID DEFAULT generateUUIDv4(),
      organization_id UUID,
      role LowCardinality(String),
      inserted_at DateTime64(6, 'UTC'),
      updated_at DateTime64(6, 'UTC')
    ) ENGINE = MergeTree()
        ORDER BY (organization_id, user_id)
    """

    execute """
    CREATE TABLE all_types (
      id UUID DEFAULT generateUUIDv4(),
      string_attr String,
      nullable_string_attr Nullable(String),
      low_cardinality_string_attr LowCardinality(String),
      low_cardinality_nullable_string_attr LowCardinality(Nullable(String)),
      fixed_string_attr FixedString(16),
      int8_attr Int8,
      nullable_int8_attr Nullable(Int8),
      int16_attr Int16,
      nullable_int16_attr Nullable(Int16),
      int32_attr Int32,
      nullable_int32_attr Nullable(Int32),
      int64_attr Int64,
      nullable_int64_attr Nullable(Int64),
      int128_attr Int128,
      nullable_int128_attr Nullable(Int128),
      int256_attr Int256,
      nullable_int256_attr Nullable(Int256),
      uint8_attr UInt8,
      nullable_uint8_attr Nullable(UInt8),
      uint16_attr UInt16,
      nullable_uint16_attr Nullable(UInt16),
      uint32_attr UInt32,
      nullable_uint32_attr Nullable(UInt32),
      uint64_attr UInt64,
      nullable_uint64_attr Nullable(UInt64),
      uint128_attr UInt128,
      nullable_uint128_attr Nullable(UInt128),
      uint256_attr UInt256,
      nullable_uint256_attr Nullable(UInt256),
      float32_attr Float32,
      nullable_float32_attr Nullable(Float32),
      float64_attr Float64,
      nullable_float64_attr Nullable(Float64),
      bool_attr Bool,
      atom_attr LowCardinality(String),
      date_attr Date,
      nullable_date_attr Nullable(Date),
      date32_attr Date32,
      datetime_attr DateTime('UTC'),
      datetime64_attr DateTime64(6, 'UTC'),
      decimal_attr Decimal(10, 2),
      decimal32_attr Decimal32(9),
      nullable_decimal32_attr Nullable(Decimal32(9)),
      decimal64_attr Decimal64(18),
      nullable_decimal64_attr Nullable(Decimal64(18)),
      decimal128_attr Decimal128(38),
      nullable_decimal128_attr Nullable(Decimal128(38)),
      decimal256_attr Decimal256(76),
      nullable_decimal256_attr Nullable(Decimal256(76)),
      json_attr JSON,
      nullable_json_attr Nullable(JSON),
      map_attr Map(String, String),
      map_attr_with_nullable_str_values Map(String, Nullable(String)),
      ipv4_attr IPv4,
      nullable_ipv4_attr Nullable(IPv4),
      ipv6_attr IPv6,
      nullable_ipv6_attr Nullable(IPv6),
      uuid_attr UUID,
      nullable_uuid_attr Nullable(UUID),
      tuple_attr Tuple(String, Int32, Bool),
      point_attr Point,
      ring_attr Ring,
      polygon_attr Polygon,
      multipolygon_attr MultiPolygon,
      simple_agg_func_attr SimpleAggregateFunction(sum, Int64),
      variant_attr Variant(Bool, Int32, String),
      array_of_string_attr Array(String),
      array_of_low_cardinality_string_attr Array(LowCardinality(String)),
      array_of_nullable_string_attr Array(Nullable(String)),
      array_of_low_cardinality_nullable_string_attr Array(LowCardinality(Nullable(String))),
      array_of_int32_attr Array(Int32),
      array_of_nullable_int32_attr Array(Nullable(Int32)),
      array_of_int64_attr Array(Int64),
      array_of_nullable_int64_attr Array(Nullable(Int64)),
      array_of_uint32_attr Array(UInt32),
      array_of_nullable_uint32_attr Array(Nullable(UInt32)),
      array_of_uint64_attr Array(UInt64),
      array_of_nullable_uint64_attr Array(Nullable(UInt64)),
      array_of_float32_attr Array(Float32),
      array_of_nullable_float32_attr Array(Nullable(Float32)),
      array_of_float64_attr Array(Float64),
      array_of_nullable_float64_attr Array(Nullable(Float64)),
      array_of_bool_attr Array(Bool),
      array_of_date_attr Array(Date),
      array_of_nullable_date_attr Array(Nullable(Date)),
      array_of_date32_attr Array(Date32),
      array_of_nullable_date32_attr Array(Nullable(Date32)),
      array_of_datetime_attr Array(DateTime('UTC')),
      array_of_nullable_datetime_attr Array(Nullable(DateTime('UTC'))),
      array_of_datetime64_attr Array(DateTime64(6, 'UTC')),
      array_of_nullable_datetime64_attr Array(Nullable(DateTime64(6, 'UTC'))),
      array_of_decimal32_attr Array(Decimal32(9)),
      array_of_nullable_decimal32_attr Array(Nullable(Decimal32(9))),
      array_of_decimal64_attr Array(Decimal64(18)),
      array_of_nullable_decimal64_attr Array(Nullable(Decimal64(18))),
      array_of_decimal128_attr Array(Decimal128(38)),
      array_of_nullable_decimal128_attr Array(Nullable(Decimal128(38))),
      array_of_decimal256_attr Array(Decimal256(76)),
      array_of_nullable_decimal256_attr Array(Nullable(Decimal256(76))),
      array_of_json_attr Array(JSON),
      array_of_nullable_json_attr Array(Nullable(JSON)),
      array_of_map_attr Array(Map(String, String)),
      array_of_ipv4_attr Array(IPv4),
      array_of_nullable_ipv4_attr Array(Nullable(IPv4)),
      array_of_ipv6_attr Array(IPv6),
      array_of_nullable_ipv6_attr Array(Nullable(IPv6)),
      array_of_uuid_attr Array(UUID),
      array_of_nullable_uuid_attr Array(Nullable(UUID)),
      array_of_variant_attr Array(Variant(Bool, Int32, String)),
      array_of_tuple_attr Array(Tuple(String, Int32, Bool)),
      array_of_point_attr Array(Point),
      array_of_ring_attr Array(Ring),
      array_of_polygon_attr Array(Polygon),
      array_of_multipolygon_attr Array(MultiPolygon)
    ) ENGINE = MergeTree()
        ORDER BY id
    """
  end

  def down do
    execute "DROP TABLE all_types"
    execute "DROP TABLE organization_users"
    execute "DROP TABLE organizations"
    execute "DROP TABLE users"
  end
end
